import React, { useState, useMemo } from 'react';
import {
  Box, Typography, Stack, Chip, Avatar, Tooltip, IconButton,
  Button, Card, Grid, Divider, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, MenuItem, Select,
  FormControl, InputLabel, LinearProgress, Paper,
  Snackbar, Alert, Badge, Menu, InputAdornment, Tabs, Tab,
  ToggleButton, ToggleButtonGroup
} from '@mui/material';
import {
  AddOutlined, CheckCircleOutlined, RadioButtonUncheckedOutlined,
  FlagOutlined, AccessTimeOutlined, PersonOutlined, MoreVertOutlined,
  CloseOutlined, EditOutlined, DeleteOutlined, SearchOutlined,
  FilterListOutlined, AutoAwesomeOutlined, LinkOutlined,
  TrendingUpOutlined, WarningAmberOutlined, AssignmentOutlined,
  PendingActionsOutlined, TaskAltOutlined, DragIndicatorOutlined,
  KeyboardArrowDownOutlined, RepeatOutlined, NotificationsOutlined,
  BarChartOutlined, ViewKanbanOutlined, ListOutlined,
  CalendarMonthOutlined, ArrowForwardOutlined, CircleOutlined
} from '@mui/icons-material';

// ─── Types ────────────────────────────────────────────────────────────────────

type Priority   = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
type TaskStatus = 'OPEN' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

interface Task {
  id: string;
  title: string;
  description?: string;
  priority: Priority;
  assignedTo: string;
  dueDate: string;
  relatedLead?: string;
  relatedBooking?: string;
  status: TaskStatus;
  createdDate: string;
  autoGenerated?: boolean;
  tags?: string[];
  subtasks?: { id: string; title: string; done: boolean }[];
  comments?: number;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const P_COLOR: Record<Priority, string>   = { LOW: '#22c55e', MEDIUM: '#eab308', HIGH: '#f97316', URGENT: '#ef4444' };
const P_BG:    Record<Priority, string>   = { LOW: '#f0fdf4', MEDIUM: '#fefce8', HIGH: '#fff7ed', URGENT: '#fef2f2' };

const STATUS_META: Record<TaskStatus, { color: string; bg: string; label: string; icon: React.ReactNode }> = {
  OPEN:        { color: '#6b7280', bg: '#f9fafb',  label: 'Open',        icon: <CircleOutlined sx={{ fontSize: 14 }} /> },
  IN_PROGRESS: { color: '#2563eb', bg: '#eff6ff',  label: 'In Progress', icon: <PendingActionsOutlined sx={{ fontSize: 14 }} /> },
  COMPLETED:   { color: '#16a34a', bg: '#f0fdf4',  label: 'Completed',   icon: <CheckCircleOutlined sx={{ fontSize: 14 }} /> },
  CANCELLED:   { color: '#9ca3af', bg: '#f3f4f6',  label: 'Cancelled',   icon: <CloseOutlined sx={{ fontSize: 14 }} /> },
};

const AGENTS = ['Me (You)', 'Rahul Sharma', 'Priya Mehta', 'Arjun Singh', 'Kavita Joshi'];

// ─── Helpers ──────────────────────────────────────────────────────────────────

const TODAY    = new Date();
const isoDate  = (d: Date) => d.toISOString().split('T')[0];
const addDays  = (d: Date, n: number) => { const r = new Date(d); r.setDate(r.getDate() + n); return r; };
const fmtDate  = (iso: string) => new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
const isPast   = (iso: string) => iso < isoDate(TODAY) ;
const avatarBg = (n: string)  => ['#7c3aed','#0891b2','#be185d','#b45309','#15803d'][n.charCodeAt(0) % 5];
const initials = (n: string)  => n.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase();

// ─── Mock Data ────────────────────────────────────────────────────────────────

const INITIAL_TASKS: Task[] = [
  {
    id: 'T1', title: 'Call Sunita Verma – 2BHK follow-up',
    priority: 'HIGH', assignedTo: 'Me (You)', dueDate: isoDate(TODAY), status: 'OPEN',
    createdDate: isoDate(addDays(TODAY, -1)), relatedLead: 'Lead #L-091',
    tags: ['follow-up', 'hot-lead'], description: 'Discuss 2BHK pricing and unit availability in Orchid Heights.',
    subtasks: [{ id:'s1', title:'Check unit availability', done:true }, { id:'s2', title:'Prepare price sheet', done:false }],
    comments: 2,
  },
  {
    id: 'T2', title: 'Send payment link to Ravi Patel',
    priority: 'URGENT', assignedTo: 'Me (You)', dueDate: isoDate(TODAY), status: 'IN_PROGRESS',
    createdDate: isoDate(addDays(TODAY, -2)), relatedBooking: 'BK-028', autoGenerated: true,
    tags: ['payment'],
  },
  {
    id: 'T3', title: 'Upload booking agreement for BK-031',
    priority: 'HIGH', assignedTo: 'Arjun Singh', dueDate: isoDate(addDays(TODAY, -1)), status: 'OPEN',
    createdDate: isoDate(addDays(TODAY, -3)), relatedBooking: 'BK-031', autoGenerated: true,
  },
  {
    id: 'T4', title: 'Prepare project brochure for site visit',
    priority: 'MEDIUM', assignedTo: 'Me (You)', dueDate: isoDate(addDays(TODAY, 1)), status: 'OPEN',
    createdDate: isoDate(TODAY),
    subtasks: [{ id:'s3', title:'Download latest floorplans', done:true }, { id:'s4', title:'Update pricing in brochure', done:false }],
  },
  {
    id: 'T5', title: 'Review RERA docs – Elite Realty',
    priority: 'MEDIUM', assignedTo: 'Priya Mehta', dueDate: isoDate(addDays(TODAY, 2)), status: 'IN_PROGRESS',
    createdDate: isoDate(TODAY), relatedLead: 'Deal #D-055', tags: ['legal'], comments: 3,
  },
  {
    id: 'T6', title: 'Follow up on deal registration approval',
    priority: 'LOW', assignedTo: 'Rahul Sharma', dueDate: isoDate(addDays(TODAY, 3)), status: 'OPEN',
    createdDate: isoDate(TODAY),
  },
  {
    id: 'T7', title: 'Weekly sales report compilation',
    priority: 'MEDIUM', assignedTo: 'Me (You)', dueDate: isoDate(addDays(TODAY, 5)), status: 'COMPLETED',
    createdDate: isoDate(addDays(TODAY, -5)),
  },
  {
    id: 'T8', title: 'Collect KYC documents from Meena Shah',
    priority: 'HIGH', assignedTo: 'Kavita Joshi', dueDate: isoDate(addDays(TODAY, 1)), status: 'IN_PROGRESS',
    createdDate: isoDate(TODAY), relatedLead: 'Lead #L-112', tags: ['kyc', 'docs'],
  },
  {
    id: 'T9', title: 'Update CRM notes after site visit',
    priority: 'LOW', assignedTo: 'Me (You)', dueDate: isoDate(addDays(TODAY, 2)), status: 'OPEN',
    createdDate: isoDate(TODAY),
  },
  {
    id: 'T10', title: 'Schedule Q3 review with finance team',
    priority: 'MEDIUM', assignedTo: 'Rahul Sharma', dueDate: isoDate(addDays(TODAY, 4)), status: 'OPEN',
    createdDate: isoDate(addDays(TODAY, -1)),
  },
];

// ─── TaskCard ─────────────────────────────────────────────────────────────────

const TaskCard: React.FC<{
  task: Task;
  onToggle: (id: string) => void;
  onStatusChange: (id: string, s: TaskStatus) => void;
  onDelete: (id: string) => void;
  onClick: () => void;
  view: 'list' | 'kanban';
}> = ({ task, onToggle, onStatusChange, onDelete, onClick, view }) => {
  const [menuAnchor, setMenuAnchor] = useState<null | HTMLElement>(null);
  const overdue = isPast(task.dueDate) && task.status !== 'COMPLETED' && task.status !== 'CANCELLED';
  const completed = task.status === 'COMPLETED';
  const doneSubs = task.subtasks?.filter(s => s.done).length ?? 0;
  const totalSubs = task.subtasks?.length ?? 0;

  return (
    <Card sx={{
      border: '1px solid',
      borderColor: overdue ? '#fca5a540' : completed ? '#bbf7d040' : '#f1f5f9',
      borderRadius: 3,
      bgcolor: overdue ? '#fff8f8' : completed ? '#f8fffe' : 'white',
      boxShadow: 'none',
      cursor: 'pointer',
      transition: 'all 0.18s ease',
      opacity: completed ? 0.7 : 1,
      '&:hover': {
        boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
        transform: view === 'list' ? 'translateX(3px)' : 'translateY(-2px)',
        borderColor: P_COLOR[task.priority] + '60',
      }
    }}>
      <Box sx={{ height: 3, bgcolor: P_COLOR[task.priority], borderRadius: '3px 3px 0 0', opacity: completed ? 0.3 : 1 }} />
      <Box sx={{ p: view === 'kanban' ? 2 : 1.8 }} onClick={onClick}>
        <Stack direction="row" spacing={1.5} alignItems="flex-start">
          <Box sx={{ pt: 0.2, flexShrink: 0 }} onClick={e => { e.stopPropagation(); onToggle(task.id); }}>
            {completed
              ? <CheckCircleOutlined sx={{ fontSize: 20, color: '#16a34a' }} />
              : <RadioButtonUncheckedOutlined sx={{ fontSize: 20, color: '#d1d5db' }} />}
          </Box>
          <Box flex={1} minWidth={0}>
            <Stack direction="row" spacing={0.8} alignItems="flex-start" flexWrap="wrap" mb={0.5}>
              <Typography sx={{
                fontSize: 13, fontWeight: 700, color: completed ? '#9ca3af' : '#111827',
                textDecoration: completed ? 'line-through' : 'none',
                lineHeight: 1.35, flex: 1,
              }}>
                {task.title}
              </Typography>
            </Stack>

            {task.description && (
              <Typography sx={{ fontSize: 11.5, color: '#9ca3af', mb: 1, lineHeight: 1.4 }} noWrap>{task.description}</Typography>
            )}

            {/* Subtask progress */}
            {totalSubs > 0 && (
              <Box mb={1.2}>
                <Stack direction="row" justifyContent="space-between" mb={0.4}>
                  <Typography sx={{ fontSize: 10, color: '#9ca3af', fontWeight: 600 }}>Subtasks</Typography>
                  <Typography sx={{ fontSize: 10, fontWeight: 800, color: doneSubs === totalSubs ? '#16a34a' : '#6b7280' }}>{doneSubs}/{totalSubs}</Typography>
                </Stack>
                <LinearProgress variant="determinate" value={(doneSubs / totalSubs) * 100}
                  sx={{ height: 4, borderRadius: 2, bgcolor: '#f1f5f9', '& .MuiLinearProgress-bar': { bgcolor: doneSubs === totalSubs ? '#16a34a' : '#3b82f6', borderRadius: 2 } }} />
              </Box>
            )}

            <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap">
              <Stack direction="row" spacing={0.4} alignItems="center">
                <Box sx={{ width: 7, height: 7, borderRadius: '50%', bgcolor: P_COLOR[task.priority], flexShrink: 0 }} />
                <Typography sx={{ fontSize: 10.5, fontWeight: 800, color: P_COLOR[task.priority] }}>{task.priority}</Typography>
              </Stack>
              <Stack direction="row" spacing={0.4} alignItems="center">
                <AccessTimeOutlined sx={{ fontSize: 11, color: overdue ? '#ef4444' : '#9ca3af' }} />
                <Typography sx={{ fontSize: 10.5, fontWeight: 600, color: overdue ? '#ef4444' : '#9ca3af' }}>
                  {overdue ? 'Overdue · ' : ''}{fmtDate(task.dueDate)}
                </Typography>
              </Stack>
              <Stack direction="row" spacing={0.4} alignItems="center">
                <Avatar sx={{ width: 16, height: 16, fontSize: 8, fontWeight: 800, bgcolor: avatarBg(task.assignedTo) }}>
                  {initials(task.assignedTo)}
                </Avatar>
                <Typography sx={{ fontSize: 10, color: '#9ca3af' }}>{task.assignedTo.split(' ')[0]}</Typography>
              </Stack>
              {task.autoGenerated && (
                <Chip label="Auto" size="small" sx={{ fontSize: 9, height: 15, bgcolor: '#eef2ff', color: '#6366f1', fontWeight: 800 }} />
              )}
              {task.tags?.map(t => (
                <Chip key={t} label={t} size="small" sx={{ fontSize: 9, height: 15, bgcolor: '#f8fafc', color: '#6b7280', fontWeight: 700, border: '1px solid #e5e7eb' }} />
              ))}
            </Stack>
          </Box>

          <Box sx={{ flexShrink: 0 }} onClick={e => e.stopPropagation()}>
            <IconButton size="small" onClick={e => { setMenuAnchor(e.currentTarget); }}
              sx={{ '&:hover': { bgcolor: '#f3f4f6' }, p: 0.4 }}>
              <MoreVertOutlined sx={{ fontSize: 15, color: '#9ca3af' }} />
            </IconButton>
          </Box>
        </Stack>
      </Box>

      <Menu anchorEl={menuAnchor} open={Boolean(menuAnchor)} onClose={() => setMenuAnchor(null)}
        PaperProps={{ sx: { borderRadius: 3, boxShadow: '0 8px 32px rgba(0,0,0,0.12)', minWidth: 180 } }}>
        {(['OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'] as TaskStatus[]).map(s => (
          <MenuItem key={s} dense onClick={() => { onStatusChange(task.id, s); setMenuAnchor(null); }}
            sx={{ fontSize: 12, fontWeight: 700, gap: 1, color: STATUS_META[s].color }}>
            <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: STATUS_META[s].color }} />
            Mark as {STATUS_META[s].label}
          </MenuItem>
        ))}
        <Divider />
        <MenuItem dense sx={{ fontSize: 12, fontWeight: 700, color: '#ef4444', gap: 1 }}
          onClick={() => { onDelete(task.id); setMenuAnchor(null); }}>
          <DeleteOutlined fontSize="small" />Delete
        </MenuItem>
      </Menu>
    </Card>
  );
};

// ─── Main Page ────────────────────────────────────────────────────────────────

const TasksPage: React.FC = () => {
  const [tasks, setTasks]           = useState<Task[]>(INITIAL_TASKS);
  const [view, setView]             = useState<'list' | 'kanban'>('list');
  const [search, setSearch]         = useState('');
  const [filterPri, setFilterPri]   = useState<Priority | 'ALL'>('ALL');
  const [filterAgent, setFilterAgent] = useState('ALL');
  const [selected, setSelected]     = useState<Task | null>(null);
  const [detailOpen, setDetailOpen] = useState(false);
  const [formOpen, setFormOpen]     = useState(false);
  const [form, setForm]             = useState<Partial<Task>>({ priority: 'MEDIUM', assignedTo: 'Me (You)', status: 'OPEN' });
  const [snack, setSnack]           = useState({ open: false, msg: '', sev: 'success' as 'success' | 'error' | 'info' });
  const [activeTab, setActiveTab]   = useState(0); // 0=tasks, 1=analytics

  // ── Derived ──────────────────────────────────────────────────────────────────
  const stats = useMemo(() => ({
    total:      tasks.length,
    open:       tasks.filter(t => t.status === 'OPEN').length,
    inProgress: tasks.filter(t => t.status === 'IN_PROGRESS').length,
    completed:  tasks.filter(t => t.status === 'COMPLETED').length,
    overdue:    tasks.filter(t => isPast(t.dueDate) && t.status !== 'COMPLETED' && t.status !== 'CANCELLED').length,
    today:      tasks.filter(t => t.dueDate === isoDate(TODAY) && t.status !== 'COMPLETED').length,
    urgent:     tasks.filter(t => t.priority === 'URGENT' && t.status !== 'COMPLETED').length,
    autoGen:    tasks.filter(t => t.autoGenerated).length,
  }), [tasks]);

  const filtered = useMemo(() => {
    let list = [...tasks];
    if (search) { const q = search.toLowerCase(); list = list.filter(t => t.title.toLowerCase().includes(q) || t.assignedTo.toLowerCase().includes(q) || t.tags?.some(tg => tg.includes(q))); }
    if (filterPri !== 'ALL') list = list.filter(t => t.priority === filterPri);
    if (filterAgent !== 'ALL') list = list.filter(t => t.assignedTo === filterAgent);
    const PO: Record<Priority, number> = { URGENT: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
    list.sort((a, b) => {
      if (a.status === 'COMPLETED' && b.status !== 'COMPLETED') return 1;
      if (b.status === 'COMPLETED' && a.status !== 'COMPLETED') return -1;
      return PO[a.priority] - PO[b.priority];
    });
    return list;
  }, [tasks, search, filterPri, filterAgent]);

  const tasksByStatus = useMemo(() => ({
    OPEN:        filtered.filter(t => t.status === 'OPEN'),
    IN_PROGRESS: filtered.filter(t => t.status === 'IN_PROGRESS'),
    COMPLETED:   filtered.filter(t => t.status === 'COMPLETED'),
    CANCELLED:   filtered.filter(t => t.status === 'CANCELLED'),
  }), [filtered]);

  const grouped = useMemo(() => ({
    overdue:   filtered.filter(t => isPast(t.dueDate) && t.status !== 'COMPLETED' && t.status !== 'CANCELLED'),
    today:     filtered.filter(t => t.dueDate === isoDate(TODAY) && t.status !== 'COMPLETED' && !isPast(t.dueDate)),
    upcoming:  filtered.filter(t => t.dueDate > isoDate(TODAY) && t.status !== 'COMPLETED'),
    completed: filtered.filter(t => t.status === 'COMPLETED'),
  }), [filtered]);

  // ── Actions ───────────────────────────────────────────────────────────────────
  const toggleTask = (id: string) => {
    setTasks(p => p.map(t => t.id === id ? { ...t, status: t.status === 'COMPLETED' ? 'OPEN' : 'COMPLETED' } : t));
  };
  const changeStatus = (id: string, status: TaskStatus) => {
    setTasks(p => p.map(t => t.id === id ? { ...t, status } : t));
    setSnack({ open: true, msg: `Task marked as ${STATUS_META[status].label}`, sev: 'success' });
  };
  const deleteTask = (id: string) => {
    setTasks(p => p.filter(t => t.id !== id));
    setDetailOpen(false);
    setSnack({ open: true, msg: 'Task deleted', sev: 'error' });
  };
  const saveTask = () => {
    if (!form.title || !form.dueDate) return;
    const t: Task = {
      id: `T${Date.now()}`, title: form.title!, priority: form.priority as Priority,
      assignedTo: form.assignedTo!, dueDate: form.dueDate!, status: 'OPEN',
      createdDate: isoDate(TODAY), description: form.description,
      relatedLead: form.relatedLead, relatedBooking: form.relatedBooking,
    };
    setTasks(p => [...p, t]);
    setFormOpen(false);
    setForm({ priority: 'MEDIUM', assignedTo: 'Me (You)', status: 'OPEN' });
    setSnack({ open: true, msg: 'Task created', sev: 'success' });
  };

  const agentStats = useMemo(() => AGENTS.map(a => ({
    name: a,
    total: tasks.filter(t => t.assignedTo === a).length,
    done:  tasks.filter(t => t.assignedTo === a && t.status === 'COMPLETED').length,
    open:  tasks.filter(t => t.assignedTo === a && t.status !== 'COMPLETED' && t.status !== 'CANCELLED').length,
  })).filter(a => a.total > 0), [tasks]);

  // ─── RENDER ─────────────────────────────────────────────────────────────────

  return (
    <Box sx={{ bgcolor: '#0f172a', minHeight: '100vh', pb: 6 }}>

      {/* ══ HEADER ═════════════════════════════════════════════════════════ */}
      <Box sx={{ px: { xs: 2, md: 4 }, pt: 4, pb: 3 }}>
        <Stack direction="row" justifyContent="space-between" alignItems="flex-start" flexWrap="wrap" gap={2} mb={3}>
          <Box>
            <Typography sx={{ fontSize: 28, fontWeight: 900, color: 'white', letterSpacing: -1.2, lineHeight: 1 }}>
              Task Management
            </Typography>
            <Typography sx={{ color: '#64748b', fontSize: 13, fontWeight: 500, mt: 0.5 }}>
              {stats.open + stats.inProgress} active · {stats.overdue} overdue · {stats.completed}/{stats.total} completed
            </Typography>
          </Box>
          <Button variant="contained" startIcon={<AddOutlined />} onClick={() => setFormOpen(true)}
            sx={{ textTransform: 'none', fontWeight: 800, borderRadius: 2.5, bgcolor: '#6366f1', '&:hover': { bgcolor: '#4f46e5' }, boxShadow: 'none' }}>
            New Task
          </Button>
        </Stack>

        {/* Stats strip */}
        <Grid container spacing={2}>
          {[
            { label: 'Open', val: stats.open,       color: '#94a3b8', icon: <CircleOutlined sx={{ fontSize: 16 }} /> },
            { label: 'In Progress', val: stats.inProgress, color: '#60a5fa', icon: <PendingActionsOutlined sx={{ fontSize: 16 }} /> },
            { label: 'Overdue', val: stats.overdue,  color: '#f87171', icon: <WarningAmberOutlined sx={{ fontSize: 16 }} /> },
            { label: 'Due Today', val: stats.today,  color: '#fbbf24', icon: <AccessTimeOutlined sx={{ fontSize: 16 }} /> },
            { label: 'Urgent', val: stats.urgent,   color: '#fb923c', icon: <FlagOutlined sx={{ fontSize: 16 }} /> },
            { label: 'Completed', val: stats.completed, color: '#4ade80', icon: <CheckCircleOutlined sx={{ fontSize: 16 }} /> },
          ].map(s => (
            <Grid item xs={4} sm={2} key={s.label}>
              <Box sx={{ p: 2, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155', textAlign: 'center' }}>
                <Box sx={{ color: s.color, display: 'flex', justifyContent: 'center', mb: 0.5 }}>{s.icon}</Box>
                <Typography sx={{ fontSize: 22, fontWeight: 900, color: s.color, letterSpacing: -1, lineHeight: 1 }}>{s.val}</Typography>
                <Typography sx={{ fontSize: 10, color: '#475569', fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.5, mt: 0.3 }}>{s.label}</Typography>
              </Box>
            </Grid>
          ))}
        </Grid>

        {/* Progress bar */}
        <Box sx={{ mt: 2.5, p: 2.5, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155' }}>
          <Stack direction="row" justifyContent="space-between" mb={1}>
            <Typography sx={{ fontSize: 12, fontWeight: 700, color: '#94a3b8' }}>Overall Progress</Typography>
            <Typography sx={{ fontSize: 13, fontWeight: 900, color: '#4ade80' }}>
              {stats.total > 0 ? Math.round((stats.completed / stats.total) * 100) : 0}%
            </Typography>
          </Stack>
          <Box sx={{ height: 8, borderRadius: 4, bgcolor: '#334155', overflow: 'hidden' }}>
            <Box sx={{
              height: '100%', borderRadius: 4,
              width: `${stats.total > 0 ? (stats.completed / stats.total) * 100 : 0}%`,
              background: 'linear-gradient(90deg, #4ade80 0%, #22c55e 100%)',
              transition: 'width 0.5s ease',
            }} />
          </Box>
          <Typography sx={{ fontSize: 11, color: '#475569', mt: 0.8 }}>{stats.completed} of {stats.total} tasks done</Typography>
        </Box>
      </Box>

      {/* ══ TABS + TOOLBAR ══════════════════════════════════════════════════ */}
      <Box sx={{ px: { xs: 2, md: 4 }, pb: 2 }}>
        <Stack direction="row" justifyContent="space-between" alignItems="center" flexWrap="wrap" gap={2} mb={2}>
          <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)}
            sx={{
              '& .MuiTab-root': { textTransform: 'none', fontWeight: 700, fontSize: 13, color: '#475569', minHeight: 40 },
              '& .MuiTabs-indicator': { bgcolor: '#6366f1', height: 3, borderRadius: 2 },
              '& .Mui-selected': { color: '#a5b4fc !important' },
            }}>
            <Tab label="All Tasks" icon={<ListOutlined sx={{ fontSize: 16 }} />} iconPosition="start" />
            <Tab label="Analytics" icon={<BarChartOutlined sx={{ fontSize: 16 }} />} iconPosition="start" />
          </Tabs>

          {activeTab === 0 && (
            <Stack direction="row" spacing={1}>
              <ToggleButtonGroup value={view} exclusive onChange={(_, v) => v && setView(v)} size="small">
                <ToggleButton value="list" sx={{ px: 1.5, color: '#475569', '&.Mui-selected': { bgcolor: '#1e3a5f', color: '#60a5fa', borderColor: '#2563eb' } }}>
                  <ListOutlined sx={{ fontSize: 16 }} />
                </ToggleButton>
                <ToggleButton value="kanban" sx={{ px: 1.5, color: '#475569', '&.Mui-selected': { bgcolor: '#1e3a5f', color: '#60a5fa', borderColor: '#2563eb' } }}>
                  <ViewKanbanOutlined sx={{ fontSize: 16 }} />
                </ToggleButton>
              </ToggleButtonGroup>
            </Stack>
          )}
        </Stack>

        {/* Filters (list view) */}
        {activeTab === 0 && (
          <Stack direction="row" spacing={1.5} flexWrap="wrap" alignItems="center">
            <TextField size="small" placeholder="Search tasks…"
              value={search} onChange={e => setSearch(e.target.value)}
              InputProps={{ startAdornment: <InputAdornment position="start"><SearchOutlined sx={{ fontSize: 16, color: '#475569' }} /></InputAdornment> }}
              sx={{ flex: 1, minWidth: 200,
                '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#1e293b', color: 'white', '& fieldset': { borderColor: '#334155' }, '&:hover fieldset': { borderColor: '#475569' } },
                '& .MuiInputBase-input::placeholder': { color: '#475569' },
              }} />

            <Select size="small" value={filterPri} onChange={e => setFilterPri(e.target.value as any)}
              sx={{ minWidth: 130, borderRadius: 2.5, bgcolor: '#1e293b', color: '#94a3b8', '& .MuiOutlinedInput-notchedOutline': { borderColor: '#334155' }, '& .MuiSvgIcon-root': { color: '#475569' } }}>
              <MenuItem value="ALL">All Priorities</MenuItem>
              {(['URGENT', 'HIGH', 'MEDIUM', 'LOW'] as Priority[]).map(p => (
                <MenuItem key={p} value={p}>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: P_COLOR[p] }} />
                    {p}
                  </Stack>
                </MenuItem>
              ))}
            </Select>

            <Select size="small" value={filterAgent} onChange={e => setFilterAgent(e.target.value)}
              sx={{ minWidth: 150, borderRadius: 2.5, bgcolor: '#1e293b', color: '#94a3b8', '& .MuiOutlinedInput-notchedOutline': { borderColor: '#334155' }, '& .MuiSvgIcon-root': { color: '#475569' } }}>
              <MenuItem value="ALL">All Agents</MenuItem>
              {AGENTS.map(a => <MenuItem key={a} value={a}>{a}</MenuItem>)}
            </Select>

            <Typography sx={{ fontSize: 12, color: '#475569', fontWeight: 600 }}>{filtered.length} tasks</Typography>
          </Stack>
        )}
      </Box>

      {/* ══ CONTENT ════════════════════════════════════════════════════════ */}
      <Box sx={{ px: { xs: 2, md: 4 } }}>

        {/* ── ANALYTICS TAB ── */}
        {activeTab === 1 && (
          <Stack spacing={3}>
            {/* By Priority */}
            <Box sx={{ p: 3, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155' }}>
              <Typography sx={{ fontSize: 14, fontWeight: 800, color: 'white', mb: 2.5 }}>Tasks by Priority</Typography>
              <Stack spacing={2}>
                {(['URGENT','HIGH','MEDIUM','LOW'] as Priority[]).map(p => {
                  const count = tasks.filter(t => t.priority === p).length;
                  const pct = tasks.length ? (count / tasks.length) * 100 : 0;
                  return (
                    <Stack key={p} direction="row" spacing={2} alignItems="center">
                      <Stack direction="row" spacing={0.8} alignItems="center" sx={{ width: 80, flexShrink: 0 }}>
                        <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: P_COLOR[p] }} />
                        <Typography sx={{ fontSize: 11, fontWeight: 800, color: P_COLOR[p] }}>{p}</Typography>
                      </Stack>
                      <Box flex={1} sx={{ height: 8, borderRadius: 4, bgcolor: '#334155', overflow: 'hidden' }}>
                        <Box sx={{ height: '100%', width: `${pct}%`, bgcolor: P_COLOR[p], borderRadius: 4, transition: 'width 0.5s' }} />
                      </Box>
                      <Typography sx={{ fontSize: 12, fontWeight: 900, color: '#94a3b8', width: 40, textAlign: 'right' }}>{count}</Typography>
                    </Stack>
                  );
                })}
              </Stack>
            </Box>

            {/* By Status */}
            <Box sx={{ p: 3, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155' }}>
              <Typography sx={{ fontSize: 14, fontWeight: 800, color: 'white', mb: 2.5 }}>Tasks by Status</Typography>
              <Grid container spacing={2}>
                {(['OPEN','IN_PROGRESS','COMPLETED','CANCELLED'] as TaskStatus[]).map(s => {
                  const count = tasks.filter(t => t.status === s).length;
                  const m = STATUS_META[s];
                  return (
                    <Grid item xs={6} sm={3} key={s}>
                      <Box sx={{ p: 2, borderRadius: 2.5, bgcolor: '#0f172a', border: `1px solid ${m.color}30`, textAlign: 'center' }}>
                        <Typography sx={{ fontSize: 28, fontWeight: 900, color: m.color, letterSpacing: -1 }}>{count}</Typography>
                        <Typography sx={{ fontSize: 11, fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: 0.5 }}>{m.label}</Typography>
                      </Box>
                    </Grid>
                  );
                })}
              </Grid>
            </Box>

            {/* Agent productivity */}
            <Box sx={{ p: 3, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155' }}>
              <Typography sx={{ fontSize: 14, fontWeight: 800, color: 'white', mb: 2.5 }}>Agent Productivity</Typography>
              <Stack spacing={2}>
                {agentStats.sort((a, b) => b.total - a.total).map(ag => (
                  <Stack key={ag.name} direction="row" spacing={2} alignItems="center">
                    <Avatar sx={{ width: 32, height: 32, fontSize: 11, fontWeight: 800, bgcolor: avatarBg(ag.name) }}>{initials(ag.name)}</Avatar>
                    <Box flex={1}>
                      <Stack direction="row" justifyContent="space-between" mb={0.5}>
                        <Typography sx={{ fontSize: 12, fontWeight: 700, color: '#e2e8f0' }}>{ag.name}</Typography>
                        <Typography sx={{ fontSize: 11, fontWeight: 800, color: '#4ade80' }}>
                          {ag.total > 0 ? Math.round((ag.done / ag.total) * 100) : 0}% done
                        </Typography>
                      </Stack>
                      <Box sx={{ height: 6, borderRadius: 3, bgcolor: '#334155', overflow: 'hidden' }}>
                        <Box sx={{ height: '100%', width: `${ag.total > 0 ? (ag.done / ag.total) * 100 : 0}%`, bgcolor: '#4ade80', borderRadius: 3, transition: 'width 0.5s' }} />
                      </Box>
                    </Box>
                    <Stack direction="row" spacing={1}>
                      <Chip label={`${ag.open} open`} size="small" sx={{ fontSize: 9, height: 18, bgcolor: '#334155', color: '#94a3b8', fontWeight: 700 }} />
                      <Chip label={`${ag.done} done`} size="small" sx={{ fontSize: 9, height: 18, bgcolor: '#14532d40', color: '#4ade80', fontWeight: 700 }} />
                    </Stack>
                  </Stack>
                ))}
              </Stack>
            </Box>
          </Stack>
        )}

        {/* ── LIST VIEW ── */}
        {activeTab === 0 && view === 'list' && (
          <Stack spacing={3}>
            {[
              { key: 'overdue', label: 'Overdue', tasks: grouped.overdue, accent: '#f87171', dot: '#ef4444' },
              { key: 'today', label: 'Due Today', tasks: grouped.today, accent: '#fbbf24', dot: '#f59e0b' },
              { key: 'upcoming', label: 'Upcoming', tasks: grouped.upcoming, accent: '#60a5fa', dot: '#3b82f6' },
              { key: 'completed', label: 'Completed', tasks: grouped.completed, accent: '#4ade80', dot: '#22c55e' },
            ].map(group => group.tasks.length > 0 && (
              <Box key={group.key}>
                <Stack direction="row" spacing={1.5} alignItems="center" mb={1.5}>
                  <Box sx={{ width: 10, height: 10, borderRadius: '50%', bgcolor: group.dot }} />
                  <Typography sx={{ fontSize: 12, fontWeight: 800, color: group.accent, textTransform: 'uppercase', letterSpacing: 1 }}>
                    {group.label}
                  </Typography>
                  <Box sx={{ height: 1, flex: 1, bgcolor: '#1e293b' }} />
                  <Box sx={{ px: 1.5, py: 0.3, borderRadius: 10, bgcolor: '#1e293b', border: '1px solid #334155' }}>
                    <Typography sx={{ fontSize: 11, fontWeight: 800, color: '#475569' }}>{group.tasks.length}</Typography>
                  </Box>
                </Stack>
                <Stack spacing={1}>
                  {group.tasks.map(t => (
                    <TaskCard key={t.id} task={t} view="list"
                      onToggle={toggleTask}
                      onStatusChange={changeStatus}
                      onDelete={deleteTask}
                      onClick={() => { setSelected(t); setDetailOpen(true); }} />
                  ))}
                </Stack>
              </Box>
            ))}
            {filtered.length === 0 && (
              <Box sx={{ textAlign: 'center', py: 8 }}>
                <TaskAltOutlined sx={{ fontSize: 48, color: '#1e293b' }} />
                <Typography sx={{ color: '#334155', fontWeight: 700, mt: 1 }}>No tasks found</Typography>
              </Box>
            )}
          </Stack>
        )}

        {/* ── KANBAN VIEW ── */}
        {activeTab === 0 && view === 'kanban' && (
          <Box sx={{ overflowX: 'auto', pb: 2 }}>
            <Stack direction="row" spacing={2.5} sx={{ minWidth: 900 }}>
              {(['OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'] as TaskStatus[]).map(status => {
                const m = STATUS_META[status];
                const col = tasksByStatus[status];
                return (
                  <Box key={status} sx={{ flex: 1, minWidth: 240 }}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center" mb={1.5}>
                      <Stack direction="row" spacing={1} alignItems="center">
                        <Box sx={{ color: m.color }}>{m.icon}</Box>
                        <Typography sx={{ fontSize: 12, fontWeight: 800, color: m.color, textTransform: 'uppercase', letterSpacing: 0.8 }}>{m.label}</Typography>
                      </Stack>
                      <Box sx={{ px: 1.5, py: 0.2, borderRadius: 10, bgcolor: '#1e293b', border: '1px solid #334155' }}>
                        <Typography sx={{ fontSize: 11, fontWeight: 800, color: '#475569' }}>{col.length}</Typography>
                      </Box>
                    </Stack>
                    <Box sx={{ p: 1.5, borderRadius: 3, bgcolor: '#1e293b', border: '1px solid #334155', minHeight: 200 }}>
                      <Stack spacing={1.2}>
                        {col.map(t => (
                          <TaskCard key={t.id} task={t} view="kanban"
                            onToggle={toggleTask}
                            onStatusChange={changeStatus}
                            onDelete={deleteTask}
                            onClick={() => { setSelected(t); setDetailOpen(true); }} />
                        ))}
                        {col.length === 0 && (
                          <Box sx={{ textAlign: 'center', py: 4 }}>
                            <Typography sx={{ fontSize: 11, color: '#334155', fontStyle: 'italic' }}>No tasks</Typography>
                          </Box>
                        )}
                      </Stack>
                    </Box>
                  </Box>
                );
              })}
            </Stack>
          </Box>
        )}
      </Box>

      {/* ══ TASK DETAIL DIALOG ═════════════════════════════════════════════ */}
      <Dialog open={detailOpen} onClose={() => setDetailOpen(false)} maxWidth="sm" fullWidth
        PaperProps={{ sx: { borderRadius: 4, bgcolor: '#1e293b', border: '1px solid #334155' } }}>
        {selected && (
          <>
            <Box sx={{ height: 4, bgcolor: P_COLOR[selected.priority] }} />
            <DialogTitle sx={{ pb: 1 }}>
              <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
                <Box flex={1} pr={1}>
                  <Stack direction="row" spacing={0.8} alignItems="center" mb={0.5}>
                    <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: P_COLOR[selected.priority] }} />
                    <Chip label={selected.priority} size="small" sx={{ fontSize: 10, height: 18, bgcolor: P_BG[selected.priority], color: P_COLOR[selected.priority], fontWeight: 800 }} />
                    <Chip label={STATUS_META[selected.status].label} size="small" sx={{ fontSize: 10, height: 18, bgcolor: STATUS_META[selected.status].bg, color: STATUS_META[selected.status].color, fontWeight: 800 }} />
                    {selected.autoGenerated && <Chip label="Auto-generated" size="small" sx={{ fontSize: 10, height: 18, bgcolor: '#eef2ff', color: '#6366f1', fontWeight: 800 }} />}
                  </Stack>
                  <Typography sx={{ fontWeight: 900, fontSize: 16, color: 'white', lineHeight: 1.3 }}>{selected.title}</Typography>
                </Box>
                <IconButton size="small" onClick={() => setDetailOpen(false)} sx={{ color: '#475569' }}><CloseOutlined /></IconButton>
              </Stack>
            </DialogTitle>
            <DialogContent>
              <Stack spacing={2.5}>
                {selected.description && (
                  <Box sx={{ p: 2, borderRadius: 2.5, bgcolor: '#0f172a', border: '1px solid #334155' }}>
                    <Typography sx={{ fontSize: 13, color: '#94a3b8', lineHeight: 1.6 }}>{selected.description}</Typography>
                  </Box>
                )}
                <Grid container spacing={2}>
                  {[
                    { label: 'Due Date', value: fmtDate(selected.dueDate), warn: isPast(selected.dueDate) && selected.status !== 'COMPLETED' },
                    { label: 'Assigned To', value: selected.assignedTo },
                    ...(selected.relatedLead ? [{ label: 'Related Lead', value: selected.relatedLead }] : []),
                    ...(selected.relatedBooking ? [{ label: 'Booking', value: selected.relatedBooking }] : []),
                    { label: 'Created', value: fmtDate(selected.createdDate) },
                  ].map(r => (
                    <Grid item xs={6} key={r.label}>
                      <Typography sx={{ fontSize: 10, fontWeight: 700, color: '#475569', textTransform: 'uppercase', letterSpacing: 0.6, mb: 0.3 }}>{r.label}</Typography>
                      <Typography sx={{ fontWeight: 800, color: (r as any).warn ? '#f87171' : '#e2e8f0', fontSize: 13 }}>{r.value}</Typography>
                    </Grid>
                  ))}
                </Grid>

                {/* Subtasks */}
                {selected.subtasks && selected.subtasks.length > 0 && (
                  <Box>
                    <Typography sx={{ fontSize: 12, fontWeight: 800, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 0.8, mb: 1.2 }}>Subtasks</Typography>
                    <Stack spacing={0.8}>
                      {selected.subtasks.map(sub => (
                        <Stack key={sub.id} direction="row" spacing={1.2} alignItems="center" sx={{ p: 1.2, borderRadius: 2, bgcolor: '#0f172a', border: '1px solid #334155' }}>
                          {sub.done ? <CheckCircleOutlined sx={{ fontSize: 16, color: '#4ade80' }} /> : <RadioButtonUncheckedOutlined sx={{ fontSize: 16, color: '#334155' }} />}
                          <Typography sx={{ fontSize: 12, color: sub.done ? '#475569' : '#e2e8f0', textDecoration: sub.done ? 'line-through' : 'none', fontWeight: 600 }}>{sub.title}</Typography>
                        </Stack>
                      ))}
                    </Stack>
                  </Box>
                )}

                {/* Tags */}
                {selected.tags && selected.tags.length > 0 && (
                  <Stack direction="row" spacing={0.8} flexWrap="wrap">
                    {selected.tags.map(t => (
                      <Chip key={t} label={`#${t}`} size="small" sx={{ fontSize: 11, fontWeight: 700, bgcolor: '#0f172a', color: '#64748b', border: '1px solid #334155' }} />
                    ))}
                  </Stack>
                )}
              </Stack>
            </DialogContent>
            <DialogActions sx={{ px: 3, pb: 3, gap: 1 }}>
              <Button onClick={() => deleteTask(selected.id)} color="error" variant="outlined"
                sx={{ textTransform: 'none', fontWeight: 700, borderRadius: 2.5, borderColor: '#7f1d1d40', color: '#f87171', '&:hover': { bgcolor: '#7f1d1d20' } }}>
                Delete
              </Button>
              <Box flex={1} />
              <Button onClick={() => { toggleTask(selected.id); setDetailOpen(false); }}
                variant="contained"
                sx={{ textTransform: 'none', fontWeight: 800, borderRadius: 2.5, bgcolor: selected.status === 'COMPLETED' ? '#d97706' : '#16a34a', '&:hover': { filter: 'brightness(0.9)', bgcolor: selected.status === 'COMPLETED' ? '#d97706' : '#16a34a' } }}>
                {selected.status === 'COMPLETED' ? 'Reopen Task' : 'Mark Complete'}
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>

      {/* ══ NEW TASK FORM ═══════════════════════════════════════════════════ */}
      <Dialog open={formOpen} onClose={() => setFormOpen(false)} maxWidth="sm" fullWidth
        PaperProps={{ sx: { borderRadius: 4, bgcolor: '#1e293b', border: '1px solid #334155' } }}>
        <DialogTitle>
          <Stack direction="row" justifyContent="space-between" alignItems="center">
            <Typography sx={{ fontWeight: 900, fontSize: 17, color: 'white' }}>New Task</Typography>
            <IconButton size="small" onClick={() => setFormOpen(false)} sx={{ color: '#475569' }}><CloseOutlined /></IconButton>
          </Stack>
        </DialogTitle>
        <DialogContent>
          <Stack spacing={2.5} mt={1}>
            <TextField label="Task Title" size="small" fullWidth value={form.title || ''}
              onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
              sx={{
                '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& fieldset': { borderColor: '#334155' } },
                '& .MuiInputLabel-root': { color: '#475569' },
              }} />
            <TextField label="Description (optional)" size="small" fullWidth multiline rows={2} value={form.description || ''}
              onChange={e => setForm(p => ({ ...p, description: e.target.value }))}
              sx={{
                '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& fieldset': { borderColor: '#334155' } },
                '& .MuiInputLabel-root': { color: '#475569' },
              }} />
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <FormControl size="small" fullWidth>
                  <InputLabel sx={{ color: '#475569' }}>Priority</InputLabel>
                  <Select value={form.priority} label="Priority" onChange={e => setForm(p => ({ ...p, priority: e.target.value as Priority }))}
                    sx={{ borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& .MuiOutlinedInput-notchedOutline': { borderColor: '#334155' }, '& .MuiSvgIcon-root': { color: '#475569' } }}>
                    {(['URGENT', 'HIGH', 'MEDIUM', 'LOW'] as Priority[]).map(p => (
                      <MenuItem key={p} value={p}>
                        <Stack direction="row" spacing={1} alignItems="center">
                          <Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: P_COLOR[p] }} />
                          {p}
                        </Stack>
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={6}>
                <TextField label="Due Date" size="small" fullWidth type="date" InputLabelProps={{ shrink: true }}
                  value={form.dueDate || ''} onChange={e => setForm(p => ({ ...p, dueDate: e.target.value }))}
                  sx={{
                    '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& fieldset': { borderColor: '#334155' } },
                    '& .MuiInputLabel-root': { color: '#475569' },
                  }} />
              </Grid>
              <Grid item xs={12}>
                <FormControl size="small" fullWidth>
                  <InputLabel sx={{ color: '#475569' }}>Assign To</InputLabel>
                  <Select value={form.assignedTo} label="Assign To" onChange={e => setForm(p => ({ ...p, assignedTo: e.target.value }))}
                    sx={{ borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& .MuiOutlinedInput-notchedOutline': { borderColor: '#334155' }, '& .MuiSvgIcon-root': { color: '#475569' } }}>
                    {AGENTS.map(a => <MenuItem key={a} value={a}>{a}</MenuItem>)}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={6}>
                <TextField label="Related Lead (optional)" size="small" fullWidth value={form.relatedLead || ''}
                  onChange={e => setForm(p => ({ ...p, relatedLead: e.target.value }))}
                  sx={{
                    '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& fieldset': { borderColor: '#334155' } },
                    '& .MuiInputLabel-root': { color: '#475569' },
                  }} />
              </Grid>
              <Grid item xs={6}>
                <TextField label="Related Booking (optional)" size="small" fullWidth value={form.relatedBooking || ''}
                  onChange={e => setForm(p => ({ ...p, relatedBooking: e.target.value }))}
                  sx={{
                    '& .MuiOutlinedInput-root': { borderRadius: 2.5, bgcolor: '#0f172a', color: 'white', '& fieldset': { borderColor: '#334155' } },
                    '& .MuiInputLabel-root': { color: '#475569' },
                  }} />
              </Grid>
            </Grid>
          </Stack>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 3 }}>
          <Button onClick={() => setFormOpen(false)} sx={{ textTransform: 'none', fontWeight: 700, color: '#475569' }}>Cancel</Button>
          <Button variant="contained" onClick={saveTask} disabled={!form.title || !form.dueDate}
            sx={{ textTransform: 'none', fontWeight: 800, borderRadius: 2.5, bgcolor: '#6366f1', '&:hover': { bgcolor: '#4f46e5' } }}>
            Create Task
          </Button>
        </DialogActions>
      </Dialog>

      <Snackbar open={snack.open} autoHideDuration={3000} onClose={() => setSnack(s => ({ ...s, open: false }))}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}>
        <Alert severity={snack.sev} sx={{ borderRadius: 3, fontWeight: 700 }} onClose={() => setSnack(s => ({ ...s, open: false }))}>
          {snack.msg}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default TasksPage;